name: Test Coverage

on:
  # Run on pushes to these branches
  push:
    branches:
      - master
      - feature/*
      - develop
  # Run on pull requests to these branches
  pull_request:
    branches:
      - master
      - feature/*
      - develop
  # Allow manual trigger
  workflow_dispatch:

# Permissions needed for GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # First job: Run tests and generate coverage report
  test-coverage:
    name: Run Tests with Coverage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests with coverage
        run: |
          pytest --cov=backend --cov-report=html tests/
          
      - name: Upload coverage reports artifact
        if: github.ref == 'refs/heads/master'
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: htmlcov/
          retention-days: 7

  # Second job: Deploy coverage report to GitHub Pages
  deploy:
    name: Deploy Coverage Report
    needs: test-coverage
    # Only deploy from master branch
    if: github.ref == 'refs/heads/master'
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Download coverage reports
        uses: actions/download-artifact@v4
        with:
          name: coverage-report
          path: htmlcov/
      
      - name: Setup Pages
        uses: actions/configure-pages@v3
        
      - name: Upload pages artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: './htmlcov'
          
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
