name: Test Coverage

on:
  push:
    branches:
      - master
      - feature/*
      - develop
  pull_request:
    branches:
      - master
      - feature/*
      - develop

jobs:
  test-coverage:
    name: Run Tests with Coverage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests with coverage
        run: |
          pytest --cov=backend --cov-report=xml --cov-report=html tests/

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          file: ./coverage.xml
          fail_ci_if_error: false

      - name: Deploy coverage report to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        if: github.ref == 'refs/heads/develop' || github.ref == 'refs/heads/master'
        with:
          folder: htmlcov
          branch: gh-pages
          clean: true